AllCops:
  NewCops: enable

  Exclude:
    - bin/**/*
    - db/schema.rb
    - .gemspec/**/*
    - .bundle/**/*
    - vendor/**/*
    - db/migrate/**/*
    - '**/dummy**/*'
    - !ruby/regexp /old_and_unused\.rb$/

Metrics/ClassLength:
  CountComments: false
  Max: 500

Layout/LineLength:
  Max: 99

Metrics/CyclomaticComplexity:
  Enabled: false

Naming/FileName:
  Exclude:
    - '*.gemspec'

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Naming/MemoizedInstanceVariableName:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false
