name: Push Gem

on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  push:
    if: github.repository_owner == 'mensfeld'
    runs-on: ubuntu-latest
    environment: deployment

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@f02c009132dc7b50a5e286d2ec2394ab5d78172a
        with:
          ruby-version: '4.0.3'
          bundler-cache: false

      - name: Bundle install
        run: bundle install --jobs 4 --retry 3

      - name: Compile C extension
        run: bundle exec rake compile

      - uses: rubygems/release-gem@6317d8d1f7e28c24d28f6eff169ea854948bd9f7
